### ISSUE TITLE
Add Binary Encoding as an Option for Server Functions

### ISSUE THREAD

**Issue by benwis** [gbj/leptos#104]
So I've been digging through the leptos code, and I think I understand how server functions are processed in Leptos.
I'd like to add MessagePack as an option to encode arguments, so that binary data payloads can be more efficiently sent from client to server. I see application for this in image processing, encryption, and other things. This would also prevent us from having to use an action or handling the client side function separately.

As I understand it, the server macro in leptos_macro is responsible for annotating the function with the ServerFn trait, which creates the fn calls from preexisting boilerplate for the client and the server.

So the way I see it, I could do this like so.
1. Add a toggle to the server macro to be encoded with MessagePack
2. Edit the call_server_fn to use the different serializer on the client
3. Edit the register() function to recognize the different serializer and process it differently
4. Create an example of handle_server_fns and an example using that structure.

Does that sound reasonable? I'm debating trying to make it generalizable, but I think MessagePack is sufficient

**Comment by gbj** [comment]
Yep very reasonable. I think it makes a *ton* of sense to do it in the macro, rather than as a feature, because then you can mix and match MessagePack for one type and a URL-encoded form for another. (The form thing is good in the default case because you can use it to create an actual `<form>` that just works.)

So in your steps:

1. Add a toggle to the server macro to be encoded with MessagePack. *Perfect.*
2. Edit the call_server_fn to use the different serializer on the client. *Exactly.*
3. Edit the register() function to recognize the different serializer and process it differently. *Even better: edit `leptos::call_server_fn` in `leptos_server` to take a `Content-Type` header. Use the server macro to set this to `application/messagepack` or whatever the right mime-type would be in the line where it invokes `::leptos::call_server_fn`, depending on whether you're in form or MessagePack mode. Then the server function handler on the server can just listen for a `Content-Type` header and decode using form encoding or MessagePack, as appropriate.*
4. Create an example of handle_server_fns and an example using that structure. *See 3.*

This is a great idea. Do you want to take a crack at it with a PR?

(I'm not touching any of `leptos_server` or `leptos_macro` with this other thread-local/memory-leak thing, so there shouldn't be any conflicts)

**Comment by benwis** [comment]
I'll take a stab at it tomorrow. The macro is the weakest part for me, but I should figure out something

**Comment by benwis** [comment]
Also looks like I'll have to rework Serializable to include both

**Comment by gbj** [comment]
IIRC `Serializable` is only used in `ServerFn::Output` i.e., to serialize the return type to JSON. If you want to be able to serialize the return type with MessagePack too (not just the arguments) then there may be a couple more steps above. I don't know that you can actually use `Serializable` in that case because that's designed to work with `miniserde` and `serde-lite` as well, so only supports JSON. But could change the bound on `ServerFn::Output` to be `serde::Serialize` instead which would allow MessagePack or JSON.
