### ISSUE TITLE
HotReload will greatly improve DX

### ISSUE THREAD

**Issue by GreatGreatGreg** [gbj/leptos#121]
Authors, thank you for providing this great repo. I have relatively large rust web project in making using a rust web framework and tailwind.  I tried to use tailwind and other jsx code moving to Leptos. They work instantly and perfectly. And the Tailwind CSS IntelliSense extension in vscode works in Leptos perfectly. 

We need the instant feedback when developing web ui especially when we change CSS. The common issue is that all rust web frameworks are great except the developing experience is not as great as js/ts web ecosystem's. Further, as project grows, the feedback becomes slower and slower.

Which means Hotreload feature is very very important. I found out only 3 frameworks have HotReload: dioxus(dioxus cli), perseus and MoonZoon. I have tried all. The dioxus's hotreload feature is great. I feel that every state change will feedback about within 3 seconds which is very good in out rust web ecosystem

Could Leptos make  hotreload feature? Make own Cli with hotreload feature. Appreciate it.

**Comment by akesson** [comment]
I'm the dev behind [cargo-leptos](https://github.com/akesson/cargo-leptos) which sounds like the tool you are looking for. 

However, it seems like there is confusion about the terminology. Hot Reload afaik, means hot module reloading where a part of the WASM app is replaced without reloading the entire page. I haven't seen this for WASM projects due to its technical complexity. There is an interesting but complex solution for hot-reloading a normal rust library, see [article](https://robert.kra.hn/posts/hot-reloading-rust/) but it requires using a C-interface.

Investigating this, I saw that what I call _autoreload_ should really be called _live reload_. I raised an [issue](https://github.com/akesson/cargo-leptos/issues/17) for it.

`cargo-leptos` should be working well but it is still in an early phase so I can't guarantee any API/configuration stability, but if there are any bugs I'll try to fix them rapidly.

**Comment by gbj** [comment]
I'm a little confused by what Dioxus is actually doing. They have this `hot-reload` feature and it seems to be connected to a bunch of serialization stuff in their repo, but when I use the Dioxus CLI it behaves like normal live-reloading: i.e., it refreshes the page and doesn't preserve app state across the reload. It's possible I'm doing something wrong but yeah, I'd say use `cargo-leptos` to get what the Dioxus CLI is providing!

**Comment by GreatGreatGreg** [comment]
Cool. Thank you. Never found cargo-leptos before. I am trying it.

**Comment by GreatGreatGreg** [comment]
Thank you very much. Hotreload works great!!!  With "--csr", when I change CSS, I got instant UI feedback. 

So now I got TailwindCSS + Hotreload ( and fast UI feedback). And I got rust web!

Really appreciate it!
