### ISSUE TITLE
Update examples so they're compatible with `cargo-leptos`

### ISSUE THREAD

**Issue by gbj** [gbj/leptos#122]
We now have a great build tool released that supports things like synchronized client-server live-reloading. It would be great to update (some or all) of the examples, in particular the ones with both client and server code (`hackernews`, `counter-isomorphic`, and `todo-app-sqlite` and `todo-app-cbor` in particular) so you can use `cargo-leptos` to run them.

**Comment by GreatGreatGreg** [comment]
And you can add tailwindCSS, the most weekly downloaded CSS now.  

Leptos is becoming best rust web framwork with great developer experience! 
1. Fast: Almost fastest rust web framework according to js-framework-benchmark.
2. HotReload: Instant UI developing feedback. It's already the fastest one.
3. TailwindCSS Intellisense: Some rust web framework do not work because of micro and DSL. Leptos works perfectly.

Thank you
