### ISSUE TITLE
leptos_dom should import all web_sys features

### ISSUE THREAD

**Issue by Rick9622092** [gbj/leptos#189]
"Selection" etc features are important. We should  import all web_sys features in Cargo.toml.

[dependencies.web-sys]
version = "0.3"
features = [
  "Attr",
  "console",
  "Comment",
  "CssStyleDeclaration",
  "CustomEvent",
  "CustomEventInit",
  "Document",
  "DocumentFragment",
  "DomStringMap",
  "DomTokenList",
  "Element",
  "Event",
  "EventTarget",
  "HtmlCollection",
  "HtmlDivElement",
  "HtmlElement",
  "HtmlInputElement",
  "HtmlTemplateElement",
  "KeyboardEvent",
  "Location",
  "MutationObserver",
  "NamedNodeMap",
  "Node",
  "NodeList",
  "Performance",
  "Selection",  
......

**Comment by gbj** [comment]
I'm not sure I agree with this. Adding every web-sys feature would slow down compilation times (which is why they're feature-gated in web-sys), making every user pay for features they won't use. 

If you need a certain web-sys feature, you should add web-sys as a dependency in your own crate and enable that feature. 

I'm open to alternative perspectives but I don't think it's a good idea for the library to import more features than it needs, personally.
