### ISSUE TITLE
`view!` supporting `Option` on attributes, props, and event listeners

### ISSUE THREAD

**Issue by jquesada2016** [gbj/leptos#45]
Often when receiving optional props, it would be really convenient to allow the macro to accept option types for event handlers and such. This would also allow conditionally attaching event listeners which can become performance hits on components which are heavily reused.

**Comment by gbj** [comment]
To clarify: Do you mean optional props on a component or optional attributes on a DOM element?

Both should actually already be possible so if you have an example of where it's not working I'd be happy to take a look!

**Comment by gbj** [comment]
Sorry I didn't see the second half of the title when I posted this response, clearly.

`Option<T>` is support on attributes when `T` is a primitive type. It's supported on properties when `T` is a primitive or `JsValue`.

I don't support it on event listeners at the moment; note that Leptos is using global event delegation, so it's not actually adding an event listener on the element. (It does create the closure for the event listener once per instance and store it in the DOM, to be fair.)

For an event listener you'd actually need to support `Fn() -> Option<Fn(web_sys::Event)>` which seems a little messy to me. (Because a simple `Option<Fn(web_sys::Event)` isn't dynamic, since components don't re-run.)

**Comment by jquesada2016** [comment]
I see it does in fact work! I didn't try it because I didn't see it in the docs. It wasn't until I checked the trait implementations for `IntoAttribute` that I saw it was implemented for many primitive types.

**Comment by gbj** [comment]
Great! I'll add something to the docs, too.
