### ISSUE TITLE
Some events not firing

### ISSUE THREAD

**Issue by jquesada2016** [gbj/leptos#54]
Given the following code:

```rust
use leptos::*;
use wasm_bindgen::prelude::*;

#[wasm_bindgen(start)]
pub fn start() {
  mount_to_body(view_fn);
}

fn view_fn(cx: Scope) -> impl Mountable {
  let (focus, set_focus) = create_signal(cx, false);

  let focused = move || {
    if focus() {
      view! { cx, <p></p> }
    } else {
      view! { cx, <span /> }
    }
  };

  view! { cx,
    <div>
      <input on:focus=move |_| set_focus(true) on:blur=move |_| set_focus(false) />
      {focused}
    </div>
  }
}
```

`on:focus` and `on:blur` never fire. `on:click` does, however.

**Comment by gbj** [comment]
Oh interesting. Yeah this is because I'm using event delegation, but focus/blur don't bubble. 

I guess add_event_listener (or the view macro) needs to check whether an event is in a set of "non-bubbling" events and use a normal event listener rather than event delegation.

https://github.com/gbj/leptos/blob/b9ca0b11a2d8846a83af6a8f37af3dde23c16179/leptos_dom/src/operations.rs#L230

**Comment by jquesada2016** [comment]
Thankfully, we're in luck. [here's a list of all of them](https://stackoverflow.com/questions/5574207/html-dom-which-events-do-not-bubble). One think to keep in mind however, and those are custom events, what should one do if someone creates a custom event which does not bubble? Should there be a special syntax for this?

**Comment by gbj** [comment]
See #56. I did test this with a quick `input` example using `focus` and `blur` and the events fire.

I'm open to suggestions for an alternate syntax for custom events which don't bubble. This is tricky because technically it's only known whether any given event bubbles at runtime (by checking its `bubbles` property or whatever) but by that point it's too late (because you're catching the event within a handler that's either been delegated or not.)

Fortunately erring on the side of caution here is not a big deal, as it's a small deoptimization in any case.
