### ISSUE TITLE
Consider consolidating the `class:` notation

### ISSUE THREAD

**Issue by jquesada2016** [gbj/leptos#74]
Through experimentation, I've noticed that using CSS minification tooling that analyzes the source code for classes, such as TailwindCSS, purge CSS, and Atomic fail to recognize classes which start with `class-`, but do work with classes that start with `class:` due to notations from JS frameworks, such as Svelte. It might be a good idea to consolidate class names to always use `class:`, instead of having two seperate notations. Ideally, this should also be extended to `on:`, but is outside the scope of this issue.

These tools can be made to recognize classes prefixed by `class-`, but it might not be obvious to users.

**Comment by gbj** [comment]
The separate `class-whatever` and `on-whatever` notations were due to a limitation of `syn-rsx`, which is the crate used to parse the `view` macro, and which only allowed all dashes or all colons in an attribute name, so we couldn't have custom event names like `on:my-event`

I've had a PR merged into `syn-rsx` to allow mixed colons and dashes but need to do the work to upgrade to `syn-rsx` 0.9 if there are any other breaking changes (See issue #57)

So, I'm going to close this for now as it will be resolved once I've closed that other issue and can consolidate the syntax again.
